In [8]:
import pandas as pd
from datetime import datetime, timedelta

dp_df = pd.read_csv(r'C:\Users\Tono\BIA-Kurs-5\Gruppuppgift\20230923Fest\DimProducts.csv')
fpi_df = pd.read_csv(r'C:\Users\Tono\BIA-Kurs-5\Gruppuppgift\20230923Fest\FactProductInventory.csv')

# Filter out rows where UnitsOut == 0 in FactProductInventory
filtered_fpi_df = fpi_df[fpi_df['UnitsOut'] != 0]

# Display first few rows of the filtered DataFrame
filtered_fpi_df.head()

# Initialize an empty DataFrame for 'FactInternetSales' with the specified columns
fis_columns = ['ProductN', 'ListPurchasePrice', 'ListSellingPrice', 
               'SalesQuantity', 'SalesOrderNumber', 'OrderDate', 'InventoryMovementKey']
fis_df = pd.DataFrame(columns=fis_columns)

# Initialize SalesOrderNumber to start at 1
sales_order_number = 1

# För kåntern
one_tenth = len(filtered_fpi_df) // 10 
counter = 0 
print(f"Starting time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

progress_bar = ['.' for _ in range(10)]

# Loop through the filtered FPI rows and populate FIS
for idx, row in filtered_fpi_df.iterrows():
    # En kånter
    counter += 1
    if counter % one_tenth == 0:
        # Replace '.' with '|'
        progress_bar[(counter // one_tenth) - 1] = '|'
        print(f"Progress: [{''.join(progress_bar)}]")
        print(f"Time at this progress point: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    # Match DP.product_id with FIS.ProductN and get the corresponding ListPurchasePrice and ListSellingPrice
    matched_row = dp_df[dp_df['product_id'] == row['ProductN']].iloc[0]
    
    # Create a new row for FIS
    new_row = {
        'ProductN': row['ProductN'],
        'ListPurchasePrice': matched_row['ListPurchasePrice'],
        'ListSellingPrice': matched_row['ListSellingPrice'],
        'SalesQuantity': row['UnitsOut'],
        'SalesOrderNumber': sales_order_number,
        'OrderDate': row['MovementDate'],
        'InventoryMovementKey': row['InventoryMovementKey']
    }
    
    # Append the new row to FIS DataFrame
    fis_df = pd.concat([fis_df, pd.DataFrame([new_row])], ignore_index=True)

    
    # Increment SalesOrderNumber for next row
    sales_order_number += 1

# Show first few rows of the newly created FactInternetSales DataFrame
fis_df.head()

Starting time: 2023-09-24 04:57:29
Progress: [|.........]
Time at this progress point: 2023-09-24 04:58:52
Progress: [||........]
Time at this progress point: 2023-09-24 05:01:15
Progress: [|||.......]
Time at this progress point: 2023-09-24 05:04:47
Progress: [||||......]
Time at this progress point: 2023-09-24 05:09:18
Progress: [|||||.....]
Time at this progress point: 2023-09-24 05:14:47
Progress: [||||||....]
Time at this progress point: 2023-09-24 05:21:10
Progress: [|||||||...]
Time at this progress point: 2023-09-24 05:28:12
Progress: [||||||||..]
Time at this progress point: 2023-09-24 05:36:40
Progress: [|||||||||.]
Time at this progress point: 2023-09-24 05:46:09
Progress: [||||||||||]
Time at this progress point: 2023-09-24 05:57:22

,ProductN,ListPurchasePrice,ListSellingPrice,SalesQuantity,SalesOrderNumber,OrderDate,InventoryMovementKey
0,1,55.642015,64.002641,2,1,2020-01-01,2
1,2,86.072751,99.108264,2,2,2020-01-01,4
2,2,86.072751,99.108264,1,3,2020-01-01,5
3,3,63.449892,79.611826,2,4,2020-01-01,7
4,3,63.449892,79.611826,1,5,2020-01-01,8

In [ ]:
fis_df.to_csv('FactInternetSales.csv', index=False)